-- all staff inserts
ALTER SEQUENCE "staff_intStaffID_seq" RESTART WITH 1 INCREMENT BY 1;
INSERT INTO staff ("strPosition", "intMemberID", "intShowID") VALUES ('Lighting Designer', 1, 1);
INSERT INTO staff ("strPosition", "intMemberID", "intShowID") VALUES ('Lighting Designer', 1, 2);
INSERT INTO staff ("strPosition", "intMemberID", "intShowID") VALUES ('Lighting Designer', 1, 3);
INSERT INTO staff ("strPosition", "intMemberID", "intShowID") VALUES ('Tech Director', 1, 6);
INSERT INTO staff ("strPosition", "intMemberID", "intShowID") VALUES ('Director', 3, 6);
INSERT INTO staff ("strPosition", "intMemberID", "intShowID") VALUES ('Stage Manager', 3, 3);
INSERT INTO staff ("strPosition", "intMemberID", "intShowID") VALUES ('Director', 3, 1);
INSERT INTO staff ("strPosition", "intMemberID", "intShowID") VALUES ('Director', 4, 6);
INSERT INTO staff ("strPosition", "intMemberID", "intShowID") VALUES ('Director', 4, 3);
INSERT INTO staff ("strPosition", "intMemberID", "intShowID") VALUES ('Director', 4, 4);
INSERT INTO staff ("strPosition", "intMemberID", "intShowID") VALUES ('Tech Director', 4, 1);
INSERT INTO staff ("strPosition", "intMemberID", "intShowID") VALUES ('Scenic Designer', 4, 1);
INSERT INTO staff ("strPosition", "intMemberID", "intShowID") VALUES ('Scenic Designer', 4, 3);
INSERT INTO staff ("strPosition", "intMemberID", "intShowID") VALUES ('Lighting Designer', 9, 5);
INSERT INTO staff ("strPosition", "intMemberID", "intShowID") VALUES ('Lighting Designer', 9, 6);
INSERT INTO staff ("strPosition", "intMemberID", "intShowID") VALUES ('Lighting Designer', 10, 4);
INSERT INTO staff ("strPosition", "intMemberID", "intShowID") VALUES ('Choreographer', 20, 4);
INSERT INTO staff ("strPosition", "intMemberID", "intShowID") VALUES ('Choreographer', 20, 5);
INSERT INTO staff ("strPosition", "intMemberID", "intShowID") VALUES ('Assistant Stage Manager', 20, 6);
INSERT INTO staff ("strPosition", "intMemberID", "intShowID") VALUES ('Master Carpenter', 20, 6);
INSERT INTO staff ("strPosition", "intMemberID", "intShowID") VALUES ('Assistant Stage Manager', 21, 5);
INSERT INTO staff ("strPosition", "intMemberID", "intShowID") VALUES ('Costume Designer', 21, 5);
INSERT INTO staff ("strPosition", "intMemberID", "intShowID") VALUES ('Stage Manager', 21, 6);
INSERT INTO staff ("strPosition", "intMemberID", "intShowID") VALUES ('Choreographer', 22, 6);
INSERT INTO staff ("strPosition", "intMemberID", "intShowID") VALUES ('Scenic Designer', 23, 6);
INSERT INTO staff ("strPosition", "intMemberID", "intShowID") VALUES ('Master Carpenter', 27, 1);
INSERT INTO staff ("strPosition", "intMemberID", "intShowID") VALUES ('Scenic Designer', 27, 2);
INSERT INTO staff ("strPosition", "intMemberID", "intShowID") VALUES ('Scenic Designer', 29, 4);
INSERT INTO staff ("strPosition", "intMemberID", "intShowID") VALUES ('Master Carpenter', 29, 4);
INSERT INTO staff ("strPosition", "intMemberID", "intShowID") VALUES ('Scenic Designer', 29, 5);
INSERT INTO staff ("strPosition", "intMemberID", "intShowID") VALUES ('Tech Director', 29, 2);
INSERT INTO staff ("strPosition", "intMemberID", "intShowID") VALUES ('Tech Director', 29, 3);
INSERT INTO staff ("strPosition", "intMemberID", "intShowID") VALUES ('Master Carpenter', 30, 5);
INSERT INTO staff ("strPosition", "intMemberID", "intShowID") VALUES ('Tech Director', 30, 5);
INSERT INTO staff ("strPosition", "intMemberID", "intShowID") VALUES ('Tech Director', 30, 4);
INSERT INTO staff ("strPosition", "intMemberID", "intShowID") VALUES ('Sound Designer', 30, 1);
INSERT INTO staff ("strPosition", "intMemberID", "intShowID") VALUES ('Director', 31, 2);
INSERT INTO staff ("strPosition", "intMemberID", "intShowID") VALUES ('Stage Manager', 32, 2);
INSERT INTO staff ("strPosition", "intMemberID", "intShowID") VALUES ('Assistant Stage Manager', 33, 2);
INSERT INTO staff ("strPosition", "intMemberID", "intShowID") VALUES ('Pit Director', 34, 2);
INSERT INTO staff ("strPosition", "intMemberID", "intShowID") VALUES ('Pit Director', 35, 3);
INSERT INTO staff ("strPosition", "intMemberID", "intShowID") VALUES ('Pit Director', 36, 4);
INSERT INTO staff ("strPosition", "intMemberID", "intShowID") VALUES ('Pit Director', 37, 5);
INSERT INTO staff ("strPosition", "intMemberID", "intShowID") VALUES ('Vocal Director', 38, 5);
INSERT INTO staff ("strPosition", "intMemberID", "intShowID") VALUES ('Sound Designer', 39, 4);
INSERT INTO staff ("strPosition", "intMemberID", "intShowID") VALUES ('Vocal Director', 40, 3);
INSERT INTO staff ("strPosition", "intMemberID", "intShowID") VALUES ('Vocal Director', 41, 2);
INSERT INTO staff ("strPosition", "intMemberID", "intShowID") VALUES ('Stage Manager', 42, 1);
INSERT INTO staff ("strPosition", "intMemberID", "intShowID") VALUES ('Choreographer', 43, 1);
INSERT INTO staff ("strPosition", "intMemberID", "intShowID") VALUES ('Rehearsal Pianist', 44, 1);
INSERT INTO staff ("strPosition", "intMemberID", "intShowID") VALUES ('Rehearsal Pianist', 45, 1);
INSERT INTO staff ("strPosition", "intMemberID", "intShowID") VALUES ('Assistant Stage Manager', 46, 1);
INSERT INTO staff ("strPosition", "intMemberID", "intShowID") VALUES ('Assistant Stage Manager', 46, 3);
INSERT INTO staff ("strPosition", "intMemberID", "intShowID") VALUES ('Pit Director', 47, 1);
INSERT INTO staff ("strPosition", "intMemberID", "intShowID") VALUES ('Costume Designer', 48, 1);
INSERT INTO staff ("strPosition", "intMemberID", "intShowID") VALUES ('Props Master', 49, 1);
INSERT INTO staff ("strPosition", "intMemberID", "intShowID") VALUES ('Rehearsal Pianist', 50, 2);
INSERT INTO staff ("strPosition", "intMemberID", "intShowID") VALUES ('Rehearsal Pianist', 50, 4);
INSERT INTO staff ("strPosition", "intMemberID", "intShowID") VALUES ('Choreographer', 51, 2);
INSERT INTO staff ("strPosition", "intMemberID", "intShowID") VALUES ('Sound Designer', 52, 2);
INSERT INTO staff ("strPosition", "intMemberID", "intShowID") VALUES ('Costume Designer', 53, 2);
INSERT INTO staff ("strPosition", "intMemberID", "intShowID") VALUES ('Rehearsal Pianist', 54, 3);
INSERT INTO staff ("strPosition", "intMemberID", "intShowID") VALUES ('Choreographer', 55, 3);
INSERT INTO staff ("strPosition", "intMemberID", "intShowID") VALUES ('Sound Designer', 25, 3);
INSERT INTO staff ("strPosition", "intMemberID", "intShowID") VALUES ('Props Master', 56, 3);
INSERT INTO staff ("strPosition", "intMemberID", "intShowID") VALUES ('Costume Designer', 57, 3);
INSERT INTO staff ("strPosition", "intMemberID", "intShowID") VALUES ('Assistant Stage Manager', 58, 4);
INSERT INTO staff ("strPosition", "intMemberID", "intShowID") VALUES ('Assistant Stage Manager', 59, 4);
INSERT INTO staff ("strPosition", "intMemberID", "intShowID") VALUES ('Director', 60, 5);
INSERT INTO staff ("strPosition", "intMemberID", "intShowID") VALUES ('Stage Manager', 61, 5);
INSERT INTO staff ("strPosition", "intMemberID", "intShowID") VALUES ('Sound Designer', 62, 5);
INSERT INTO staff ("strPosition", "intMemberID", "intShowID") VALUES ('Sound Designer', 63, 6);
INSERT INTO staff ("strPosition", "intMemberID", "intShowID") VALUES ('Props Master', 63, 5);
INSERT INTO staff ("strPosition", "intMemberID", "intShowID") VALUES ('Props Master', 64, 5);
INSERT INTO staff ("strPosition", "intMemberID", "intShowID") VALUES ('Costume Designer', 65, 6);