-- all pits inserts
ALTER SEQUENCE "pits_intPitID_seq" RESTART WITH 1 INCREMENT BY 1;
INSERT INTO pits ("strInstrument", "intMemberID", "intShowID") VALUES ('Flute/Piccolo', 34, 1);
INSERT INTO pits ("strInstrument", "intMemberID", "intShowID") VALUES ('Clarinet', 89, 1);
INSERT INTO pits ("strInstrument", "intMemberID", "intShowID") VALUES ('Bassoon', 90, 1);
INSERT INTO pits ("strInstrument", "intMemberID", "intShowID") VALUES ('Horn', 91, 1);
INSERT INTO pits ("strInstrument", "intSeat", "intMemberID", "intShowID") VALUES ('Horn', 2, 92, 1);
INSERT INTO pits ("strInstrument", "intMemberID", "intShowID") VALUES ('Trumpet', 93, 1);
INSERT INTO pits ("strInstrument", "intMemberID", "intShowID") VALUES ('Piano', 94, 1);
INSERT INTO pits ("strInstrument", "intMemberID", "intShowID") VALUES ('Synthesizer', 50, 1);
INSERT INTO pits ("strInstrument", "intMemberID", "intShowID") VALUES ('Violin', 95, 1);
INSERT INTO pits ("strInstrument", "intSeat", "intMemberID", "intShowID") VALUES ('Violin', 2, 96, 1);
INSERT INTO pits ("strInstrument", "intMemberID", "intShowID") VALUES ('Viola', 97, 1);
INSERT INTO pits ("strInstrument", "intSeat", "intMemberID", "intShowID") VALUES ('Viola', 2, 98, 1);
INSERT INTO pits ("strInstrument", "intMemberID", "intShowID") VALUES ('Cello', 99, 1);
INSERT INTO pits ("strInstrument", "intMemberID", "intShowID") VALUES ('Bass', 100, 1);
INSERT INTO pits ("strInstrument", "intMemberID", "intShowID") VALUES ('Percussion', 101, 1);
INSERT INTO pits ("strInstrument", "intMemberID", "intShowID") VALUES ('Reed', 102, 3);
INSERT INTO pits ("strInstrument", "intSeat", "intMemberID", "intShowID") VALUES ('Reed', 2, 103, 3);
INSERT INTO pits ("strInstrument", "intMemberID", "intShowID") VALUES ('Trumpet', 104, 3);
INSERT INTO pits ("strInstrument", "intMemberID", "intShowID") VALUES ('Viola', 105, 3);
INSERT INTO pits ("strInstrument", "intMemberID", "intShowID") VALUES ('Cello', 106, 3);
INSERT INTO pits ("strInstrument", "intMemberID", "intShowID") VALUES ('Guitar', 108, 3);
INSERT INTO pits ("strInstrument", "intSeat", "intMemberID", "intShowID") VALUES ('Keyboard', 2, 107, 3);
INSERT INTO pits ("strInstrument", "intSeat", "intMemberID", "intShowID") VALUES ('Guitar', 2, 109, 3);
INSERT INTO pits ("strInstrument", "intMemberID", "intShowID") VALUES ('Drums', 110, 3);
INSERT INTO pits ("strInstrument", "intMemberID", "intShowID") VALUES ('Percussion', 111, 3);
INSERT INTO pits ("strInstrument", "intMemberID", "intShowID") VALUES ('Violin', 95, 3);
INSERT INTO pits ("strInstrument", "intSeat", "intMemberID", "intShowID") VALUES ('Violin', 2, 98, 3);
INSERT INTO pits ("strInstrument", "intMemberID", "intShowID") VALUES ('Keyboard', 54, 3);
INSERT INTO pits ("strInstrument", "intMemberID", "intShowID") VALUES ('Reed', 5, 3);
INSERT INTO pits ("strInstrument", "intMemberID", "intShowID") VALUES ('Bass', 50, 3);
INSERT INTO pits ("strInstrument", "intMemberID", "intShowID") VALUES ('Keyboard', 112, 2);
INSERT INTO pits ("strInstrument", "intSeat", "intMemberID", "intShowID") VALUES ('Keyboard', 2, 94, 2);
INSERT INTO pits ("strInstrument", "intMemberID", "intShowID") VALUES ('Tenor Saxophone/Baritone Saxophone', 35, 2);
INSERT INTO pits ("strInstrument", "intMemberID", "intShowID") VALUES ('Trumpet', 113, 2);
INSERT INTO pits ("strInstrument", "intMemberID", "intShowID") VALUES ('Drums', 114, 2);
INSERT INTO pits ("strInstrument", "intMemberID", "intShowID") VALUES ('Guitar', 115, 2);
INSERT INTO pits ("strInstrument", "intMemberID", "intShowID") VALUES ('Bass', 50, 2);
INSERT INTO pits ("strInstrument", "intMemberID", "intShowID") VALUES ('Bassoon', 90, 4);
INSERT INTO pits ("strInstrument", "intMemberID", "intShowID") VALUES ('Trumpet', 93, 4);
INSERT INTO pits ("strInstrument", "intSeat", "intMemberID", "intShowID") VALUES ('Trumpet', 2, 125, 4);
INSERT INTO pits ("strInstrument", "intMemberID", "intShowID") VALUES ('Bass Trombone', 99, 4);
INSERT INTO pits ("strInstrument", "intMemberID", "intShowID") VALUES ('Flute/Piccolo', 126, 4);
INSERT INTO pits ("strInstrument", "intMemberID", "intShowID") VALUES ('Oboe/English Horn', 127, 4);
INSERT INTO pits ("strInstrument", "intMemberID", "intShowID") VALUES ('Clarinet', 89, 4);
INSERT INTO pits ("strInstrument", "intMemberID", "intShowID") VALUES ('French Horn', 128, 4);
INSERT INTO pits ("strInstrument", "intSeat", "intMemberID", "intShowID") VALUES ('French Horn', 2, 129, 4);
INSERT INTO pits ("strInstrument", "intMemberID", "intShowID") VALUES ('Flute/Clarinet', 103, 4);
INSERT INTO pits ("strInstrument", "intMemberID", "intShowID") VALUES ('Clarinet/Bass Clarinet', 37, 4);
INSERT INTO pits ("strInstrument", "intMemberID", "intShowID") VALUES ('Drums', 110, 4);
INSERT INTO pits ("strInstrument", "intMemberID", "intShowID") VALUES ('Percussion', 111, 4);
INSERT INTO pits ("strInstrument", "intMemberID", "intShowID") VALUES ('Violin', 130, 4);
INSERT INTO pits ("strInstrument", "intSeat", "intMemberID", "intShowID") VALUES ('Violin', 2, 131, 4);
INSERT INTO pits ("strInstrument", "intSeat", "intMemberID", "intShowID") VALUES ('Violin', 3, 95, 4);
INSERT INTO pits ("strInstrument", "intMemberID", "intShowID") VALUES ('Cello', 104, 4);
INSERT INTO pits ("strInstrument", "intMemberID", "intShowID") VALUES ('Bass', 66, 4);
INSERT INTO pits ("strInstrument", "intMemberID", "intShowID") VALUES ('Keyboard', 132, 4);
INSERT INTO pits ("strInstrument", "intMemberID", "intShowID") VALUES ('Synthesizer', 50, 4);
INSERT INTO pits ("strInstrument", "intMemberID", "intShowID") VALUES ('Tenor Trombone', 133, 4);
INSERT INTO pits ("strInstrument", "intMemberID", "intShowID") VALUES ('Violin', 136, 5);
INSERT INTO pits ("strInstrument", "intMemberID", "intShowID") VALUES ('Reed', 16, 5);
INSERT INTO pits ("strInstrument", "intMemberID", "intShowID") VALUES ('Piano', 36, 5);
INSERT INTO pits ("strInstrument", "intMemberID", "intShowID") VALUES ('Viola', 139, 5);
INSERT INTO pits ("strInstrument", "intMemberID", "intShowID") VALUES ('Cello', 99, 5);
INSERT INTO pits ("strInstrument", "intMemberID", "intShowID") VALUES ('Bass', 15, 5);
INSERT INTO pits ("strInstrument", "intMemberID", "intShowID") VALUES ('Trumpet', 142, 5);
INSERT INTO pits ("strInstrument", "intMemberID", "intShowID") VALUES ('Horn', 92, 5);
INSERT INTO pits ("strInstrument", "intMemberID", "intShowID") VALUES ('Percussion', 141, 5);
INSERT INTO pits ("strInstrument", "intSeat", "intMemberID", "intShowID") VALUES ('Violin', 2, 137, 5);
INSERT INTO pits ("strInstrument", "intSeat", "intMemberID", "intShowID") VALUES ('Violin', 3, 138, 5);
INSERT INTO pits ("strInstrument", "intSeat", "intMemberID", "intShowID") VALUES ('Reed', 2, 143, 5);
INSERT INTO pits ("strInstrument", "intSeat", "intMemberID", "intShowID") VALUES ('Reed', 3, 112, 5);
INSERT INTO pits ("strInstrument", "intSeat", "intMemberID", "intShowID") VALUES ('Reed', 3, 144, 5);
INSERT INTO pits ("strInstrument", "intSeat", "intMemberID", "intShowID") VALUES ('Piano', 2, 140, 5);