ALTER SEQUENCE "exec_intExecID_seq" RESTART WITH 1 INCREMENT BY 1;
INSERT INTO exec ("strPosition", "intMemberID", "intDateID", "intClubID") VALUES ('President', 1, 4, 1);
INSERT INTO exec ("strPosition", "intMemberID", "intDateID", "intClubID") VALUES ('President', 1, 5, 1);
INSERT INTO exec ("strPosition", "intMemberID", "intDateID", "intClubID") VALUES ('Secretary', 1, 2, 1);
INSERT INTO exec ("strPosition", "intMemberID", "intDateID", "intClubID") VALUES ('Secretary', 1, 3, 1);
INSERT INTO exec ("strPosition", "intMemberID", "intDateID", "intClubID") VALUES ('Vice President', 2, 4, 1);
INSERT INTO exec ("strPosition", "intMemberID", "intDateID", "intClubID") VALUES ('Vice President', 2, 5, 1);
INSERT INTO exec ("strPosition", "intMemberID", "intDateID", "intClubID") VALUES ('Vice President', 4, 2, 1);
INSERT INTO exec ("strPosition", "intMemberID", "intDateID", "intClubID") VALUES ('Vice President', 4, 3, 1);
INSERT INTO exec ("strPosition", "intMemberID", "intDateID", "intClubID") VALUES ('Treasurer', 5, 4, 1);
INSERT INTO exec ("strPosition", "intMemberID", "intDateID", "intClubID") VALUES ('Treasurer', 5, 5, 1);
INSERT INTO exec ("strPosition", "intMemberID", "intDateID", "intClubID") VALUES ('Treasurer', 5, 2, 1);
INSERT INTO exec ("strPosition", "intMemberID", "intDateID", "intClubID") VALUES ('Treasurer', 5, 3, 1);
INSERT INTO exec ("strPosition", "intMemberID", "intDateID", "intClubID") VALUES ('PR Manager', 6, 4, 1);
INSERT INTO exec ("strPosition", "intMemberID", "intDateID", "intClubID") VALUES ('PR Manager', 6, 5, 1);
INSERT INTO exec ("strPosition", "intMemberID", "intDateID", "intClubID") VALUES ('Secretary', 7, 4, 1);
INSERT INTO exec ("strPosition", "intMemberID", "intDateID", "intClubID") VALUES ('Secretary', 7, 5, 1);
INSERT INTO exec ("strPosition", "intMemberID", "intDateID", "intClubID") VALUES ('Vice President', 12, 6, 1);
INSERT INTO exec ("strPosition", "intMemberID", "intDateID", "intClubID") VALUES ('President', 13, 6, 1);
INSERT INTO exec ("strPosition", "intMemberID", "intDateID", "intClubID") VALUES ('Vice President', 14, 6, 1);
INSERT INTO exec ("strPosition", "intMemberID", "intDateID", "intClubID") VALUES ('PR Manager', 15, 6, 1);
INSERT INTO exec ("strPosition", "intMemberID", "intDateID", "intClubID") VALUES ('PR Manager', 16, 6, 1);
INSERT INTO exec ("strPosition", "intMemberID", "intDateID", "intClubID") VALUES ('Secretary', 17, 6, 1);
INSERT INTO exec ("strPosition", "intMemberID", "intDateID", "intClubID") VALUES ('President', 24, 2, 1);
INSERT INTO exec ("strPosition", "intMemberID", "intDateID", "intClubID") VALUES ('President', 24, 3, 1);
INSERT INTO exec ("strPosition", "intMemberID", "intDateID", "intClubID") VALUES ('Secretary', 24, 1, 1);
INSERT INTO exec ("strPosition", "intMemberID", "intDateID", "intClubID") VALUES ('President', 25, 1, 1);
INSERT INTO exec ("strPosition", "intMemberID", "intDateID", "intClubID") VALUES ('Treasurer', 26, 1, 1);
INSERT INTO exec ("strPosition", "intMemberID", "intDateID", "intClubID") VALUES ('Vice President', 27, 1, 1);
INSERT INTO exec ("strPosition", "intMemberID", "intDateID", "intClubID") VALUES ('PR Manager', 28, 1, 1);